---
title: "Activity2"
author: "Ankita Bhattacharyya and Cayla Stevenson"
format: html
editor: visual
---

# Introduction and Background
The goal of this analysis to be able to.


# Data Exploration


# Modeling Methods


## Method One: Subset Selection Algorithms

To find variables for the model, two subset selection algorithms were used; Forward Selection with the performance indicator AIC and Backward Selection with the performance indicator BIC. Each gave difference variables to be included in the model. The backwards selection included fewer predictors than the forward selection did. To select between the two models, we did some further analysis on certain predictors in each model and the checked for violations of multi-linear assumptions.

The two base models that are being analyzed are:

Forward AIC:
```{r, eval=FALSE, echo=FALSE}
# Creating Models from Subsetting Algorithms-------------------------------
library(tidyverse)
library(Hmisc)
library(modelr)
library(caret)

insurance_data <- read.csv("insurance_data_S26.csv")

#FORWARD SELECTION (AIC)----------------------
null_insurance <- lm(
  charges ~ 1,
  data = insurance_data
)

full_insurance <-lm(
  charges ~ .,
  data = insurance_data
)

stats::step(
  object = null_insurance,
  scope = list(lower = null_insurance, upper = full_insurance),
  data = insurance_data,
  direction = 'forward'
)

FORWARD_AIC <- lm(charges~smoker+age+bmi+region+children+priorclaims+month, data = insurance_data)

#Testing Significance predictors------------------------------
#Using terminal output
FORWARD_AIC <- lm(charges~smoker+age+bmi+children+priorclaims+month, data = insurance_data)
FORWARD_AIC <- lm(charges~smoker+age+bmi+children+priorclaims, data = insurance_data)

#CROSS VALIDATION -----------------------------
View(insurance_data)

# Cross Validation (80-20 split) - 

set.seed(550)
train_index <- sample(
  x = 1:nrow(insurance_data),
  size = floor(0.8*nrow(insurance_data))
)

insuranceTrain <- insurance_data[train_index, ]
insuranceValid <- insurance_data[-train_index, ]

insuranceTrainModel <- lm(
  formula = charges ~ smoker+age+bmi+children+priorclaims,
  data = insuranceTrain
)

insuranceValid <- insuranceValid %>%
  mutate(
    model1_predict = predict(
      object = insuranceTrainModel,
      newdata = insuranceValid
    )
  )
```

$$\hat{charges} = -11437.82 + 23045.34smokeryes + 259.86age + 338.86bmi - 617.69regionnorthwest - 1950.74regionsoutheast - 1512.27regionsouthwest + 528.11children + 346.21priorclaims - 106.75month$$
Backward BIC:
$$\hat{charges} = -11627.90 + 257.65age + 310.57bmi + 502.99children + 23016.60smokeryes$$

### Significance of Predictors

When conducting a hypothesis test of significance for each predictor in Forward AIC's model, `region`'s t statistic and p-value when `region` is northwest and all other predictors are constant are -1.013 and 0.31123, respectively. Under a 5% significance level, there isn't enough evidence to say region is a significant enough predictor. The predictor is removed from the model, and the resulting model as: $$\hat{charges=}-11612.23+22996.69smokeryes+261.46age+305.57bmi+538.87children+359.47priorclaims-95.95months$$
Continuing to remove insignificant predictors, when conducting another hypothesis test for significance for each predictor in Forward AIC's model, `month`'s t-statistic and p-value are -1.547 and 0.12216 respectively. Under a 5% significance level, there isn't enough evidence to month is a significant enough predictor.
Once removed the model becomes: $$\hat{charges} = -12154.03 + 22984.80smokeryes +260.38age+304.55bmi+530.38children+355.36priorclaims$$

The resulting model's Adjusted R-squared is 0.7205. 72.05 % of the model's variation in charges is explained by predictors of smoker, age, bmi, children and prior claims.  

### Testing Multi-linearity Assumptions
Checking for departures from linearity in both models. 
 
## Method Two: Lasso Regression

# Final Reccomendations 

# Author Contributions and Responsibilities 

# Code Appendix 
```{rcodeAppend, ref.label=knitr::all_labels(), echo=TRUE, eval=FALSE}

```


```

